[paths]
ffmpeg = "ffmpeg"
slippi_playback = "~/AppData/Roaming/Slippi Launcher/playback/Slippi Dolphin.exe"
ssbm_iso = "~/Downloads/Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso"

[dolphin]
backend = "OGL"
resolution = "1080p"
bitrate = 16000

[dolphin.gecko_codes]
"$Optional: Show Player Names" = true
"$Optional: Game Music OFF" = false
"$Optional: Widescreen 16:9" = false
"$Optional: Disable Screen Shake" = false
"$Optional: Hide HUD" = false
"$Optional: Hide Waiting For Game" = true
"$Optional: Enable Develop Mode" = false
"$Optional: Lagless FoD" = false

[ffmpeg]
audio_args = "-ar 48000 -c:a libopus -f opus -ac 2 -b:a 128k"
volume = 25

[runtime]
parallel = 0
prepend_directory = true
youtubify_names = true
preserve_directory_structure = false

[runtime.name_replacements]
"-" = "–"
"(" = "⟮"
")" = "⟯"
"_" = "＿"
"<" = "＜"
">" = "＞"
"." = "．"
"/" = "／"
":" = "："
"'" = "＇"
'"' = "＂"
