[paths]
ffmpeg = "ffmpeg"
slippi_playback = "~/AppData/Roaming/Slippi Launcher/playback/Slippi Dolphin.exe"
ssbm_ini = "~/Downloads/Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso"

[video]
backend = "Software"
resolution = "1080p"
bitrate = 16000
# TODO: Volume

[runtime]
parallel = 1
