[paths]
ffmpeg = "ffmpeg"
slippi_playback = "~/AppData/Roaming/Slippi Launcher/playback/Slippi Dolphin.exe"
ssbm_iso = "~/Downloads/Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso"

[dolphin]
backend = "OGL"
resolution = "1080p"
bitrate = 16000

[ffmpeg]
audio_args = "-ar 48000 -c:a libopus -f opus -ac 2 -b:a 128k"
volume = 25

[runtime]
parallel = 0
prepend_directory = true
youtubify_names = true
preserve_directory_structure = false

[runtime.name_replacements]
"-" = "–"
"(" = "⟮"
")" = "⟯"
"_" = "＿"
"<" = "＜"
">" = "＞"
"." = "．"
"/" = "／"
":" = "："
"'" = "＇"
"\\"" = "＂"
