[paths]
ffmpeg = "ffmpeg"
slippi_playback = "~/.config/Slippi Launcher/playback/Slippi_Playback-x86_64.AppImage"
ssbm_ini = "~/Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso"

[video]
backend = "OGL"
resolution = "1080p"
bitrate = 16000
# TODO: Volume

[runtime]
parallel = 1
