[paths]
ffmpeg = "ffmpeg"
slippi_playback = "~/AppData/Roaming/Slippi Launcher/playback/Slippi Dolphin.exe"
ssbm_ini = "~/Downloads/Super Smash Bros. Melee (USA) (En,Ja) (Rev 2).iso"

[dolphin]
backend = "OGL"
resolution = "1080p"
bitrate = 16000
# TODO: Volume

[ffmpeg]
audio_args = "-ar 48000 -c:a libopus -f opus -ac 2 -b:a 128k"

[runtime]
parallel = 0
